#!/usr/bin/env python3

__version__ = "0.1.0"

import os
import sys

import cadquery as cq
from helical_thread import ThreadHelixes, helical_thread

from cq_bolt import cq_bolt
from utils import dbg, setCtx, show
from parameters import Parameters

setCtx(globals())

if __name__ == "__main__" or "cq_editor" in sys.modules:

    argv = sys.argv if "cq_editor" not in sys.modules else []
    # dbg(f"argv={argv}")

    params = Parameters(section="bolt", argv=argv[1:])
    # dbg(f"params={vars(params)}")

    ths: ThreadHelixes = helical_thread(params.ht)
    # dbg(f"ths={vars(ths)}")

    bolt = cq_bolt(ths, params.head_size, params.head_height, params.wall_thickness)
    show(bolt, "bolt-0")

    directory: str = "generated/"
    fname = f"bolt-dia_{params.dia_major:.3f}-p_{params.ht.pitch:.3f}-a_{params.ht.angle_degs:.3f}-h_{params.ht.height:.3f}-hs_{params.head_size:3f}-mj_{params.ht.major_cutoff:.3f}-mi_{params.ht.minor_cutoff:.3f}-ec_{params.ht.ext_clearance:.3f}-to_{params.ht.thread_overlap:.4f}-tol_{params.stl_tolerance:.3f}.stl"
    cq.exporters.export(bolt, os.path.join(directory, fname), tolerance=params.stl_tolerance)
    dbg(f"{fname}")
